const TransferActionTypes = {
  INIT_TRANSFER: 'INIT_TRANSFER',
  VALIDATE_TRANSFER: 'VALIDATE_TRANSFER',
  RESEND_OTP_TRANSFER: 'RESEND_OTP_TRANSFER',
  GET_FAVORITES_TRANSFER: 'GET_FAVORITES_TRANSFER',
  GET_HISTORY_TRANSFER: 'GET_HISTORY_TRANSFER',
};

export default TransferActionTypes;
