const CashTransferActionTypes = {
  INIT_CASH_TRANSFER: 'INIT_CASH_TRANSFER',
  VALIDATE_CASH_TRANSFER: 'VALIDATE_CASH_TRANSFER',
  RESEND_OTP_CASH_TRANSFER: 'RESEND_OTP_CASH_TRANSFER',
  GET_FAVORITES_CASH_TRANSFER: 'GET_FAVORITES_CASH_TRANSFER',
  GET_HISTORY_CASH_TRANSFER: 'GET_HISTORY_CASH_TRANSFER',
};

export default CashTransferActionTypes;
