const BeneficiariesActionTypes = {
  GET_ALL_BENEFICIARIES: 'GET_ALL_BENEFICIARIES',
  GET_TRANSFER_BENEFICIARIES: 'GET_TRANSFER_BENEFICIARIES',
  GET_CASH_TRANSFER_BENEFICIARIES: 'GET_CASH_TRANSFER_BENEFICIARIES',
};

export default BeneficiariesActionTypes;
